AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.6

Metrics/BlockLength:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'spec/**/*.rb'
Style/AndOr:
  EnforcedStyle: conditionals
